- name: Install and configure zabbix agent
  hosts: tags_zabbix-agent
  become: true

  tasks:
    # install packages
    - name: install packages
      apt:
        state: present
        name:
          - zabbix-agent
          - tcpdump
          - qemu-guest-agent  
          #- ntp
          #- ntpdate

    - name: inside etc/hosts, change hostname to real ip, not loopback 
      lineinfile:
        path: /etc/hosts
        state: present
        line: "{{ item }}"
      with_items:
        - "{{ primary_ip4 }} {{ ansible_fqdn }} {{ inventory_hostname }}"
        
    - name: Comment out default /etc/hosts
      lineinfile:
        path: /etc/hosts
        state: absent
        line: "{{ item }}"
      with_items:
        - "127.0.1.1 {{ ansible_fqdn }} {{ inventory_hostname }}"
        
    # ZABBIX
    - name: Zabbix - Remove zabbix server loopback
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        state: absent        
        line: "{{ item }}"
      with_items:
        - 'Server=127.0.0.1'
        - 'ServerActive=127.0.0.1'

    # ZABBIX
    - name: Zabbix - Remove zabbix old Metadata
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        state: absent        
        regexp: '^HostMetadata'
      
    - name: Zabbix - Configure zabbix server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        state: present
        line: "{{ item }}"
      with_items:
        - 'Server=monitor.golesuite.com'
        - 'ServerActive=monitor.golesuite.com'
        - "Hostname={{ ansible_fqdn }}"
        - "HostMetadata=platform:{{ platforms[0] }} - tenant:{{ tenants[0] }} - device_role:{{ device_roles[0] }} - {{ tags }}"
        
    - name: start_restart_zabbix_agent
      service:
        name: zabbix-agent
        state: restarted
        enabled: yes
        
  # handlers:
  #   # this tasks is to ensure ntp service is started
  #   - name: start_restart_ntp_client
  #     service:
  #       name=ntpd
  #       state=restarted
  #       enabled=yes
  #   - name: start_restart_zabbix_agent
  #     service:
  #       name=zabbix-agent
  #       state=restarted
  #       enabled=yes
